# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  host:     localhost
  username: postgres
  password: Vivek91$

development:
  <<: *default
  database: sudoku_development

test:
  <<: *default
  database: <%= ENV.fetch('PGDATABASE', 'sudoku_test') %>

production:
  <<: *default
  database: sudoku_production
